// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function APIRequest(arg1:string,arg2:string,arg3:string):Promise<main.APIResponse>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function Port():Promise<number>;
