// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIRequest(arg1, arg2, arg3) {
  return window['go']['main']['Desktop']['APIRequest'](arg1, arg2, arg3);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['Desktop']['OpenExternalURL'](arg1);
}

export function Port() {
  return window['go']['main']['Desktop']['Port']();
}
